// This file is auto-generated by @hey-api/openapi-ts

export const AnalyticsResponseSchema = {
    properties: {
        summary: {
            '$ref': '#/components/schemas/AnalyticsSummary'
        },
        daily_deliveries: {
            items: {
                '$ref': '#/components/schemas/DailyDeliveryStat'
            },
            type: 'array',
            title: 'Daily Deliveries'
        }
    },
    type: 'object',
    required: ['summary', 'daily_deliveries'],
    title: 'AnalyticsResponse'
} as const;

export const AnalyticsSummarySchema = {
    properties: {
        total_deliveries: {
            type: 'integer',
            title: 'Total Deliveries'
        },
        pending: {
            type: 'integer',
            title: 'Pending'
        },
        in_transit: {
            type: 'integer',
            title: 'In Transit'
        },
        delivered: {
            type: 'integer',
            title: 'Delivered'
        },
        cancelled: {
            type: 'integer',
            title: 'Cancelled'
        },
        completion_rate: {
            type: 'number',
            title: 'Completion Rate'
        }
    },
    type: 'object',
    required: ['total_deliveries', 'pending', 'in_transit', 'delivered', 'cancelled', 'completion_rate'],
    title: 'AnalyticsSummary'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CoordinateSchema = {
    properties: {
        latitude: {
            type: 'number',
            maximum: 90,
            minimum: -90,
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            maximum: 180,
            minimum: -180,
            title: 'Longitude'
        }
    },
    type: 'object',
    required: ['latitude', 'longitude'],
    title: 'Coordinate'
} as const;

export const DailyDeliveryStatSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['date', 'count'],
    title: 'DailyDeliveryStat'
} as const;

export const DeliveriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DeliveryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DeliveriesPublic'
} as const;

export const DeliveryCreateSchema = {
    properties: {
        customer_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Customer Name'
        },
        latitude: {
            type: 'number',
            maximum: 90,
            minimum: -90,
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            maximum: 180,
            minimum: -180,
            title: 'Longitude'
        },
        status: {
            '$ref': '#/components/schemas/DeliveryStatus',
            default: 'PENDING'
        }
    },
    type: 'object',
    required: ['customer_name', 'latitude', 'longitude'],
    title: 'DeliveryCreate'
} as const;

export const DeliveryLocationSchema = {
    properties: {
        latitude: {
            type: 'number',
            maximum: 90,
            minimum: -90,
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            maximum: 180,
            minimum: -180,
            title: 'Longitude'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['latitude', 'longitude', 'id'],
    title: 'DeliveryLocation'
} as const;

export const DeliveryPublicSchema = {
    properties: {
        customer_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Customer Name'
        },
        latitude: {
            type: 'number',
            maximum: 90,
            minimum: -90,
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            maximum: 180,
            minimum: -180,
            title: 'Longitude'
        },
        status: {
            '$ref': '#/components/schemas/DeliveryStatus',
            default: 'PENDING'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['customer_name', 'latitude', 'longitude', 'id', 'owner_id'],
    title: 'DeliveryPublic'
} as const;

export const DeliveryStatusSchema = {
    type: 'string',
    enum: ['PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED'],
    title: 'DeliveryStatus'
} as const;

export const DeliveryUpdateSchema = {
    properties: {
        customer_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DeliveryStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'DeliveryUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RouteOptimizationRequestSchema = {
    properties: {
        warehouse: {
            '$ref': '#/components/schemas/Coordinate'
        },
        deliveries: {
            items: {
                '$ref': '#/components/schemas/DeliveryLocation'
            },
            type: 'array',
            title: 'Deliveries'
        }
    },
    type: 'object',
    required: ['warehouse', 'deliveries'],
    title: 'RouteOptimizationRequest'
} as const;

export const RouteOptimizationResponseSchema = {
    properties: {
        optimized_route: {
            items: {
                '$ref': '#/components/schemas/RouteOrder'
            },
            type: 'array',
            title: 'Optimized Route'
        },
        total_distance_km: {
            type: 'number',
            title: 'Total Distance Km'
        },
        estimated_time_minutes: {
            type: 'number',
            title: 'Estimated Time Minutes'
        }
    },
    type: 'object',
    required: ['optimized_route', 'total_distance_km', 'estimated_time_minutes'],
    title: 'RouteOptimizationResponse'
} as const;

export const RouteOrderSchema = {
    properties: {
        delivery_id: {
            type: 'string',
            format: 'uuid',
            title: 'Delivery Id'
        },
        order: {
            type: 'integer',
            title: 'Order'
        }
    },
    type: 'object',
    required: ['delivery_id', 'order'],
    title: 'RouteOrder'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;