// This file is auto-generated by @hey-api/openapi-ts

export type AnalyticsResponse = {
    summary: AnalyticsSummary;
    daily_deliveries: Array<DailyDeliveryStat>;
};

export type AnalyticsSummary = {
    total_deliveries: number;
    pending: number;
    in_transit: number;
    delivered: number;
    cancelled: number;
    completion_rate: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Coordinate = {
    latitude: number;
    longitude: number;
};

export type DailyDeliveryStat = {
    date: string;
    count: number;
};

export type DeliveriesPublic = {
    data: Array<DeliveryPublic>;
    count: number;
};

export type DeliveryCreate = {
    customer_name: string;
    latitude: number;
    longitude: number;
    status?: DeliveryStatus;
};

export type DeliveryLocation = {
    latitude: number;
    longitude: number;
    id: string;
};

export type DeliveryPublic = {
    customer_name: string;
    latitude: number;
    longitude: number;
    status?: DeliveryStatus;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type DeliveryStatus = 'PENDING' | 'IN_TRANSIT' | 'DELIVERED' | 'CANCELLED';

export type DeliveryUpdate = {
    customer_name?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    status?: (DeliveryStatus | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RouteOptimizationRequest = {
    warehouse: Coordinate;
    deliveries: Array<DeliveryLocation>;
};

export type RouteOptimizationResponse = {
    optimized_route: Array<RouteOrder>;
    total_distance_km: number;
    estimated_time_minutes: number;
};

export type RouteOrder = {
    delivery_id: string;
    order: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AnalyticsGetAnalyticsResponse = (AnalyticsResponse);

export type DeliveriesReadDeliveriesData = {
    limit?: number;
    skip?: number;
};

export type DeliveriesReadDeliveriesResponse = (DeliveriesPublic);

export type DeliveriesCreateDeliveryData = {
    requestBody: DeliveryCreate;
};

export type DeliveriesCreateDeliveryResponse = (DeliveryPublic);

export type DeliveriesReadDeliveryData = {
    id: string;
};

export type DeliveriesReadDeliveryResponse = (DeliveryPublic);

export type DeliveriesUpdateDeliveryData = {
    id: string;
    requestBody: DeliveryUpdate;
};

export type DeliveriesUpdateDeliveryResponse = (DeliveryPublic);

export type DeliveriesDeleteDeliveryData = {
    id: string;
};

export type DeliveriesDeleteDeliveryResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OptimizationOptimizeDeliveryRouteData = {
    requestBody: RouteOptimizationRequest;
};

export type OptimizationOptimizeDeliveryRouteResponse = (RouteOptimizationResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);