"""add rbac fields

Revision ID: 3332e5c91a5a
Revises: 977ac98ed7d4
Create Date: 2026-05-26 12:11:16.066185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3332e5c91a5a'
down_revision = '977ac98ed7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER', 'CUSTOMER', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('delivery', sa.Column('driver_id', sa.Uuid(), nullable=True))
    op.add_column('delivery', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'delivery', 'user', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'delivery', 'user', ['driver_id'], ['id'])
    op.add_column('user', sa.Column('role', user_role_enum, nullable=False, server_default='CUSTOMER'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    user_role_enum = sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER', 'CUSTOMER', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'customer_id')
    op.drop_column('delivery', 'driver_id')
    # ### end Alembic commands ###
